## Modified from bioconda-recipes (https://github.com/bioconda/bioconda-recipes/blob/master/config.yml) and (https://github.com/bioconda/bioconda-recipes/blob/master/scripts/env_matrix.yml)
env_matrix: "scripts/env_matrix.yaml"
 

## No current blacklist 
  
channels:
  - ggd-dev
  - bioconda
  - conda-forge
  - defaults
